volumes:
  database_volume:
  certbot_etc:
  certbot_var:

networks:
  network:

services:
  postgres:
    image: postgres:16
    container_name: postgres
    restart: no
    volumes:
      - database_volume:/var/lib/postgresql/data
    networks:
      - network
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}

  backend:
    build: backend
    container_name: backend
    restart: no
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - network
    environment:
      DATASOURCE_SERVER: postgres:5432
      DATASOURCE_DATABASE: ${DATABASE_NAME}
      DATASOURCE_USERNAME: ${DATABASE_USERNAME}
      DATASOURCE_PASSWORD: ${DATABASE_PASSWORD}

  frontend:
    build: frontend
    container_name: frontend
    restart: no
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - network
    environment:
      NODE_ENV: production
      ORIGIN: http://localhost
      PROTOCOL_HEADER: x-forwarded-proto
      HOST_HEADER: x-forwarded-host

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: no
    ports:
      - "80:80"
    #      - "443:443"
    depends_on:
      - frontend
      - backend
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - certbot_etc:/etc/letsencrypt
      - certbot_etc:/var/lib/letsencrypt
    networks:
      - network

  #  certbot:
  #    image: certbot/certbot
  #    container_name: certbot
  #    restart: no
  #    volumes:
  #      - ./proxy/default.conf:/etc/nginx/conf.d/default.conf
  #      - certbot_etc:/etc/letsencrypt
  #      - certbot_etc:/var/lib/letsencrypt
  #    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $!; done;'"

  adminer:
    image: adminer:latest
    ports:
      - "8000:8080"
    depends_on:
      - postgres
    networks:
      - network
    environment:
      ADMINER_DEFAULT_DB_DRIVER: pgsql
      ADMINER_DEFAULT_SERVER: postgres:5432
      ADMINER_DEFAULT_DATABASE: ${DATABASE_NAME}
      ADMINER_DEFAULT_USERNAME: ${DATABASE_USERNAME}
      ADMINER_DEFAULT_PASSWORD: ${DATABASE_PASSWORD}
      ADMINER_PLUGINS: "tables-filter tinymce dark-switcher"