volumes:
  database_volume:
  certbot_etc:
  certbot_var:

networks:
  network:

services:
  postgres:
    image: postgres:16
    container_name: postgres
    restart: no
    volumes:
      - database_volume:/var/lib/postgresql/data
    networks:
      - network
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    networks:
      - network
    ports:
      - "8025:8025"

  backend:
    build: backend
    container_name: backend
    depends_on:
      - postgres
      - mailhog
    restart: no
    ports:
      - "8080:8080"
    networks:
      - network
    environment:
      DATASOURCE_SERVER: postgres:5432
      DATASOURCE_DATABASE: db
      DATASOURCE_USERNAME: admin
      DATASOURCE_PASSWORD: admin
      SMTP_HOST: mailhog
      SMTP_PORT: 1025
      SMTP_USERNAME:
      SMTP_PASSWORD:

  frontend:
    build: frontend
    container_name: frontend
    depends_on:
      - backend
    networks:
      - network
    environment:
      NODE_ENV: production
      ORIGIN: http://localhost
      PROTOCOL_HEADER: x-forwarded-proto
      HOST_HEADER: x-forwarded-host

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: no
    ports:
      - "80:80"
    #      - "443:443"
    depends_on:
      - frontend
      - backend
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - certbot_etc:/etc/letsencrypt
      - certbot_var:/var/lib/letsencrypt
    networks:
      - network

  adminer:
    image: adminer:latest
    container_name: adminer
    ports:
      - "8000:8080"
    depends_on:
      - postgres
    networks:
      - network
    environment:
      ADMINER_DEFAULT_DB_DRIVER: pgsql
      ADMINER_DEFAULT_SERVER: postgres:5432
      ADMINER_DEFAULT_DATABASE: db
      ADMINER_DEFAULT_USERNAME: admin
      ADMINER_DEFAULT_PASSWORD: admin
      ADMINER_PLUGINS: "tables-filter tinymce dark-switcher"