spring:
  application:
    name: TUrtleAPI

  datasource:
    url: jdbc:postgresql://database:5432/database
    username: postgres
    password: dummy_password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    #show-sql: true
    #properties:
    #  hibernate:
    #    format_sql: true

#logging:
#  level:
#    org:
#      hibernate:
#        SQL: debug
#      springdoc: DEBUG
#      springframework:
#        web: DEBUG

server:
  port: 8080

springdoc:
  api-docs:
    path: /openapi/api-docs
  swagger-ui:
    url: /openapi/api-docs
    path: /docs
