spring:
  application:
    name: TUrtleAPI

  datasource:
    url: jdbc:postgresql://postgres:5432/postgres
    username: postgres
    password: dummy_password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update

springdoc:
  api-docs:
    path: /openapi/api-docs
  swagger-ui:
    url: /openapi/api-docs
    path: /docs
